// todo-list/src/Footer.jsx
import React from 'react';
import './App.css';

const FilterButton = ({ id, clickHandler, content, chosenFilter }) => (
    <button id={ id } onClick={ clickHandler }
            className={ (chosenFilter === id) ? "footer-button--active" : "footer-button" }>{ content }
    </button>
);

const Footer = ({clearCompleted, length, handler, chosenFilter, someIsCompleted}) => (
    <div className={ length ? "footer" : "footer-hidden" }>
        <div className="footer__counter">{ length } items left</div>
        <FilterButton id="all" clickHandler={ handler } content="All" chosenFilter={ chosenFilter }/>
        <FilterButton id="active" clickHandler={ handler } content="Active" chosenFilter={ chosenFilter }/>
        <FilterButton id="completed" clickHandler={ handler } content="Completed" chosenFilter={ chosenFilter }/>
        <button onClick={ clearCompleted } className={ someIsCompleted ? "footer-button" : "footer-button--hidden"}>Clear completed</button>
    </div>
);

export default Footer;

// test-angular/src/app/todoList/footer/footer.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.less']
})

export class FooterComponent {
  @Input() changeFilter;
  @Input() clearCompleted;
  @Input() listLength;
  @Input() numberOfCompleted;
  @Input() chosenFilter;
}

<div class="footer" [ngClass]="{'footer--hidden': !listLength}">
  <span class="footer__counter">{{ listLength - numberOfCompleted }} item left</span>
  <div class="filter" (change)="changeFilter($event)">
    <input class="filter__item" id="all" type="radio" name="filter" checked>
    <label for="all">All</label>
    <input class="filter__item" id="active"  type="radio" name="filter">
    <label for="active">Active</label>
    <input class="filter__item" id="completed" type="radio" name="filter">
    <label for="completed">Completed</label>
  </div>
  <button class="footer__clear" [ngClass]="{'footer__clear--hidden' : !numberOfCompleted}" (click)="clearCompleted()">Clear completed</button>
</div>
