// test-angular/src/app/footer/footer.component.ts
import {Component, EventEmitter, Input, OnChanges, Output} from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.less']
})
export class FooterComponent implements OnChanges {
  numberOfCompleted: number;

  @Input() list;

  @Output() clearCompleted: EventEmitter<any> = new EventEmitter();
  @Output() changeFilter: EventEmitter<any> = new EventEmitter();

  ngOnChanges() {
    this.numberOfCompleted = this.list.reduce((counter, { completed }) => {
      if (completed) {
        return counter + 1;
      } else {
        return counter;
      }
    }, 0);

  }

  onClearCompleted() {
    this.clearCompleted.emit();
  }

  onChangeFilter($event) {
    this.changeFilter.emit($event);
  }
}

<div class="footer" [ngClass]="{'footer--hidden': !list.length}">
  <span class="footer__counter">{{ list.length - numberOfCompleted }} item left</span>
  <div class="filter" (change)="onChangeFilter($event)">
    <input class="filter__item" id="all" type="radio" name="filter" checked>
    <label for="all">All</label>
    <input class="filter__item" id="active"  type="radio" name="filter">
    <label for="active">Active</label>
    <input class="filter__item" id="completed" type="radio" name="filter">
    <label for="completed">Completed</label>
  </div>
  <button class="footer__clear" [ngClass]="{'footer__clear--hidden' : !numberOfCompleted}" (click)="onClearCompleted()">Clear completed</button>
</div>

// todo-list/src/Footer/Footer.jsx
import React from 'react';
import './footer.less';
import { CSS, ID } from '../Constants';
import FilterButton from './FilterButton';

const Footer = ({ todoList, chosenFilter, changeFilter, clearCompleted }) => {
    const numberOfCompleted = todoList.reduce((counter, { completed }) => {
        if (completed) {
            return counter + 1;
        } else {
            return counter;
        }
    }, 0);

    return (
        <div className={ todoList.length ? CSS.FOOTER : CSS.FOOTER_HIDDEN }>
            <div className={ CSS.COUNTER }>{ todoList.length - numberOfCompleted } items left</div>
            <FilterButton id={ ID.ALL } changeFilter={ (event) => changeFilter(event) } content="All" chosenFilter={ chosenFilter }/>
            <FilterButton id={ ID.ACTIVE } changeFilter={ (event) => changeFilter(event) } content="Active" chosenFilter={ chosenFilter }/>
            <FilterButton id={ ID.COMPLETED } changeFilter={ (event) => changeFilter(event) } content="Completed" chosenFilter={ chosenFilter }/>
            <button id={ ID.CLEAR_COMPLETED } onClick={ () => clearCompleted() } className={ numberOfCompleted ? CSS.BUTTON : CSS.BUTTON_HIDDEN }>Clear completed</button>
        </div>
    )
};

export default Footer;
